server:
  port: 8080
  servlet:
    context-path: /identity




spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # auto update schema
    show-sql: true

jwt:
  signerKey: "Ps+SZyEwrAXj6M/xcX0vc1M+c/X4GBCjmqKr/v05uN2RvDRbW1n5HsHzBXrP21+3"